export const SPECIES = [
  {
    id: "velune",
    name: "Vélune",
    element: "nature",
    color: "#91b574",
    accent: "#f6d59a",
    shape: "leaf",
    hp: 48,
    atk: 13,
    def: 12,
    speed: 12,
    rarity: 1,
    habitat: "Clairière",
    temper: "curieuse",
    job: "Les feuillages de Vélune nourrissent la terre.",
    desc: "Un petit jardin nomade, dont les oreilles s’ouvrent avec le soleil.",
    moves: ["liane", "pollen", "garde"],
  },
  {
    id: "ondril",
    name: "Ondril",
    element: "eau",
    color: "#69b6bc",
    accent: "#f4d9a2",
    shape: "fin",
    hp: 52,
    atk: 12,
    def: 13,
    speed: 10,
    rarity: 1,
    habitat: "Rives",
    temper: "joueuse",
    job: "Ondril arrose les parcelles proches.",
    desc: "Il conserve la rosée dans sa couronne et dessine des ronds sur l’eau.",
    moves: ["onde", "brume", "garde"],
  },
  {
    id: "brasile",
    name: "Brasîle",
    element: "feu",
    color: "#d99569",
    accent: "#ffe7a9",
    shape: "ember",
    hp: 43,
    atk: 16,
    def: 9,
    speed: 14,
    rarity: 1,
    habitat: "Carrière",
    temper: "curieuse",
    job: "Sa chaleur accélère la croissance des plantes.",
    desc: "Un compagnon de terre cuite. Une braise timide bat sous sa carapace.",
    moves: ["braise", "elan", "garde"],
  },
  {
    id: "moussier",
    name: "Moussier",
    element: "terre",
    color: "#a9a573",
    accent: "#e6cfaf",
    shape: "shell",
    hp: 60,
    atk: 13,
    def: 17,
    speed: 6,
    rarity: 1,
    habitat: "Bois",
    temper: "timide",
    desc: "Il porte une mousse ancienne qui fleurit quand on lui fait confiance.",
    moves: ["roc", "pollen", "garde"],
  },
  {
    id: "vrille",
    name: "Vrillevent",
    element: "air",
    color: "#b9cbb5",
    accent: "#f6e6c1",
    shape: "wing",
    hp: 40,
    atk: 14,
    def: 9,
    speed: 19,
    rarity: 2,
    habitat: "Hauteurs",
    temper: "timide",
    desc: "Ses ailes en éventail bruissent comme les pages d’un livre.",
    moves: ["souffle", "elan", "garde"],
  },
  {
    id: "lumignon",
    name: "Lumignon",
    element: "lumiere",
    color: "#e8c87e",
    accent: "#fff0b6",
    shape: "lantern",
    hp: 46,
    atk: 16,
    def: 10,
    speed: 13,
    rarity: 3,
    habitat: "Ruines · soir",
    temper: "nocturne",
    desc: "Il rallume les souvenirs oubliés entre les pierres des anciens jardins.",
    moves: ["eclat", "brume", "garde"],
  },
  {
    id: "coralys",
    name: "Coralys",
    element: "eau",
    color: "#c48ea2",
    accent: "#b7ddd0",
    shape: "fin",
    hp: 55,
    atk: 14,
    def: 12,
    speed: 12,
    rarity: 2,
    habitat: "Rives · pluie",
    temper: "joueuse",
    desc: "Une créature de rivière aux ramures de corail végétal.",
    moves: ["onde", "pollen", "garde"],
  },
  {
    id: "gardien",
    name: "Le Veilleur de Sève",
    element: "nature",
    color: "#577f67",
    accent: "#e6ba6f",
    shape: "guardian",
    hp: 110,
    atk: 20,
    def: 17,
    speed: 8,
    rarity: 5,
    habitat: "Sanctuaire",
    temper: "territoriale",
    desc: "Le dernier jardinier des ruines. Son cœur attend que les jardins refleurissent.",
    moves: ["liane", "roc", "pollen"],
  },
];
export const MOVES = {
  liane: {
    name: "Liane vive",
    power: 21,
    energy: 5,
    element: "nature",
    accuracy: 0.96,
  },
  pollen: {
    name: "Pollen paisible",
    power: 8,
    energy: 8,
    element: "nature",
    accuracy: 0.91,
    status: "somnolent",
  },
  garde: { name: "Abri", power: 0, energy: -9, guard: true },
  onde: {
    name: "Onde claire",
    power: 22,
    energy: 5,
    element: "eau",
    accuracy: 0.98,
  },
  brume: { name: "Brume réparatrice", power: 0, energy: 9, heal: 18 },
  braise: {
    name: "Braise filante",
    power: 25,
    energy: 6,
    element: "feu",
    accuracy: 0.93,
    status: "brulure",
  },
  elan: { name: "Élan", power: 16, energy: 0, element: "air", accuracy: 1 },
  roc: {
    name: "Éclat de schiste",
    power: 25,
    energy: 6,
    element: "terre",
    accuracy: 0.9,
  },
  souffle: {
    name: "Souffle tournoyant",
    power: 23,
    energy: 5,
    element: "air",
    accuracy: 0.96,
  },
  eclat: {
    name: "Éclat d’aube",
    power: 26,
    energy: 7,
    element: "lumiere",
    accuracy: 0.98,
  },
};
export const ELEMENT_NAMES = {
  nature: "Nature",
  eau: "Eau",
  feu: "Feu",
  terre: "Terre",
  air: "Air",
  lumiere: "Lumière",
};
export const ITEMS = {
  wood: "Bois",
  stone: "Pierre",
  fiber: "Fibres",
  crystal: "Cristal de sève",
  seed: "Graines de roselle",
  crop: "Roselles",
  quality: "Roselles dorées",
  seal: "Liens de résonance",
  potion: "Tisanes",
  fish: "Truites ambrées",
  plank: "Planches",
  lamp: "Lanternes",
  fence: "Clôtures",
  bench: "Bancs",
  bed: "Jardinières",
  workbench: "Établis",
  fertilizer: "Compost",
};
export const RECIPES = [
  {
    id: "seal",
    name: "Lien de résonance",
    cost: { fiber: 3, crystal: 1 },
    count: 3,
    desc: "Un tissage de lumière pour se lier aux créatures.",
  },
  {
    id: "potion",
    name: "Tisane de roselle",
    cost: { crop: 2 },
    count: 2,
    desc: "Restaure 30 PV à un compagnon.",
  },
  {
    id: "plank",
    name: "Planche de frêne",
    cost: { wood: 2 },
    count: 1,
    desc: "Du bois pour les créations du jardin.",
  },
  {
    id: "lamp",
    name: "Lanterne des jardins",
    cost: { wood: 3, crystal: 1 },
    count: 1,
    desc: "Un halo chaleureux pour les longues soirées.",
  },
  {
    id: "fence",
    name: "Clôture tressée",
    cost: { wood: 2, fiber: 1 },
    count: 2,
    desc: "Pour dessiner votre propriété.",
  },
  {
    id: "bench",
    name: "Banc de jardin",
    cost: { wood: 5, stone: 2 },
    count: 1,
    desc: "Un endroit où regarder pousser le printemps.",
  },
  {
    id: "bed",
    name: "Jardinière fleurie",
    cost: { wood: 3, fiber: 3 },
    count: 1,
    desc: "Une profusion de fleurs pour votre maison.",
  },
  {
    id: "workbench",
    name: "Établi de campagne",
    cost: { wood: 8, stone: 4 },
    count: 1,
    desc: "Un atelier à placer sur votre terrain.",
  },
  {
    id: "fertilizer",
    name: "Compost végétal",
    cost: { fiber: 4 },
    count: 2,
    desc: "Accélère la croissance et améliore la qualité.",
  },
];
export const QUESTS = [
  {
    title: "Une lettre, un jardin",
    text: "Retrouvez Maëlle près de la fontaine. Elle a gardé les clés de votre maison.",
    test: (s) => !!s.flags.metMaelle,
  },
  {
    title: "La terre se souvient",
    text: "Rejoignez votre propriété au sud-ouest. Plantez puis arrosez trois roselles.",
    test: (s) => s.stats.planted >= 3 && s.stats.watered >= 3,
  },
  {
    title: "Une nouvelle amitié",
    text: "Explorez la clairière, affaiblissez une créature et tissez un lien de résonance.",
    test: (s) => s.stats.captured >= 1 || s.team.length >= 2,
  },
  {
    title: "Ce que le jardin nous rend",
    text: "Récoltez trois roselles, puis préparez une tisane dans le carnet de fabrication.",
    test: (s) => s.stats.harvested >= 3 && s.flags.brewed,
  },
  {
    title: "Une lumière à la fenêtre",
    text: "Récoltez du bois et du cristal. Fabriquez une lanterne puis placez-la sur votre terrain.",
    test: (s) => s.buildings.some((b) => b.type === "lamp"),
  },
  {
    title: "Le jardin des anciens",
    text: "Retrouvez le Veilleur dans les ruines, au nord-est, au-delà du grand pont.",
    test: (s) => s.flags.guardian,
  },
  {
    title: "Les jardins s’éveillent",
    text: "La première source chante de nouveau. Cultivez, liez de nouvelles amitiés et composez votre jardin.",
    test: () => false,
  },
];
export const TOOLS = [
  ["hand", "✧", "Lien"],
  ["axe", "⚒", "Hache"],
  ["pick", "⛏", "Pioche"],
  ["hoe", "♧", "Cultiver"],
  ["water", "♒", "Arroser"],
  ["build", "⌂", "Bâtir"],
  ["journal", "☷", "Carnet"],
];
export const LANDMARKS = [
  { id: "city", name: "Place des Trois Sources", x: -9, z: 1 },
  { id: "home", name: "Votre jardin", x: -29, z: 28 },
  { id: "forest", name: "Bois des Murmures", x: 40, z: 14 },
  { id: "ruins", name: "Sanctuaire de Sève", x: 42, z: -38 },
  { id: "market", name: "Marché des Tisserands", x: -30, z: -19 },
  { id: "quarry", name: "Carrière dorée", x: 39, z: 40 },
  { id: "heights", name: "Les Hauts-Vergers", x: -23, z: -48 },
];
export function species(id) {
  return SPECIES.find((c) => c.id === id) || SPECIES[0];
}
export function portrait(id) {
  const s = species(id),
    c = s.color,
    a = s.accent;
  return `<svg viewBox="0 0 120 105" aria-label="${s.name}" role="img"><ellipse cx="60" cy="92" rx="35" ry="6" fill="#24483c18"/><path d="M32 62 Q14 25 35 15 Q53 26 48 53 M72 52 Q70 16 93 14 Q110 39 83 63" fill="${a}" stroke="${c}" stroke-width="6"/><path d="M22 71 Q21 40 59 37 Q100 39 99 73 Q97 92 60 93 Q25 93 22 71" fill="${c}"/><ellipse cx="61" cy="77" rx="23" ry="14" fill="${a}"/><circle cx="43" cy="62" r="5" fill="#213e37"/><circle cx="79" cy="62" r="5" fill="#213e37"/><circle cx="44" cy="60" r="1.7" fill="white"/><circle cx="80" cy="60" r="1.7" fill="white"/><path d="M56 73q5 5 10 0" stroke="#4c5f48" fill="none" stroke-width="2"/><path d="M30 83L24 95h17 M80 87l-1 8h17" fill="${c}"/>${s.shape === "leaf" ? '<path d="M52 38Q32 2 61 7Q75 20 63 38" fill="#6b925e"/><path d="M60 33Q64 8 86 15Q91 36 60 40" fill="#c2c887"/>' : ""}${s.shape === "ember" ? '<path d="M47 38Q43 20 56 6Q54 21 69 20Q83 35 68 41" fill="#f6c982"/>' : ""}${s.shape === "lantern" ? '<circle cx="61" cy="26" r="17" fill="#fff1ac" opacity=".8"/>' : ""}</svg>`;
}
